spring:
  application:
    name: theidlenotes

  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: ${MONGO_CLUSTER_URL}
      database: globalnotesdb
      auto-index-creation: true

server:
  servlet:
    context-path: /idle-notes
  port: 8080

jwt:
  secret: ${JWT_SECRET}